/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        limablue: {
          50:  '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        "surface-container-low": "#f2f4f6",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#7b2f00",
        "outline-variant": "#c7c4d8",
        "surface-tint": "#0055d4",
        "on-error": "#ffffff",
        "tertiary": "#7e3000",
        "primary-fixed": "#dbe4f5",
        "surface": "#f7f9fb",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#001a45",
        "on-surface-variant": "#464555",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#777587",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-container": "#a44100",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#b3c4e5",
        "secondary-fixed": "#dae2fd",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0044ab",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "on-secondary-container": "#5c647a",
        "on-secondary": "#ffffff",
        "primary-container": "#0055d4",
        "background": "#f7f9fb",
        "secondary": "#565e74",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#b3c4e5",
        "tertiary-fixed-dim": "#ffb695",
        "secondary-container": "#dae2fd",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#ffd2be",
        "on-tertiary-fixed": "#351000",
        "surface-variant": "#e0e3e5",
        "primary": "#0044ab",
        "surface-container": "#eceef0",
        "on-primary-container": "#dbe4f5"
      },
      spacing: {
        "sidebar-expanded": "260px",
        "sidebar-collapsed": "72px",
        "grid-gutter": "24px",
        "container-padding": "32px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        "headline-sm": ["Geist", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        'xxs': '0.65rem',
        "headline-sm": ["18px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "500" }],
        "mono-label": ["12px", { "lineHeight": "16px", "letterSpacing": "0", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      },
      gridTemplateRows: {
        '48': 'repeat(48, minmax(0, 1fr))',
      },
    },
  },
  plugins: [],
};
